<?php

namespace ByJG\Convert;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-03 at 15:36:36.
 */
class ToUTF8Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers ByJG\Convert\ToUTF8::fromHtmlEntities
     * @todo   Implement testFromHtmlEntities().
     */
    public function testFromHtmlEntities()
    {
        $this->assertEquals(
            "Liberté Egalité Fraternité",
            ToUTF8::fromHtmlEntities("Libert&eacute; Egalit&eacute; Fraternit&eacute;")
        );

        $this->assertEquals(
            "áéíóú",
            ToUTF8::fromHtmlEntities("&aacute;&eacute;&iacute;&oacute;&uacute;")
        );

        $this->assertEquals(
            "jÚnior",
            ToUTF8::fromHtmlEntities("j&Uacute;nior")
        );

        $this->assertEquals(
            "Teste de validação de email título de email para ver se funciona",
            ToUTF8::fromHtmlEntities('Teste de valida&ccedil;&atilde;o de email t&iacute;tulo de email para ver se funciona')
        );
    }

}
